extends: default

rules:
  # comments should visibly make sense
  comments:
    level: error
  comments-indentation:
    level: error
  # 88 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 88
    level: warning
