[tox]
envlist = py312

[testenv]
extras =
    argcomplete
    aws-snapshots
    azure
    azure-snapshots
    cloud
    google
    google-snapshots
    snappy
    zstandard
    lz4
deps =
    pytest
    mock
commands = pytest {posargs:tests}
passenv = USER

[testenv:black]
deps = black
commands = black .

[testenv:coverage]
extras = 
    argcomplete
    aws-snapshots
    azure
    azure-snapshots
    cloud
    google
    google-snapshots
    snappy
    zstandard
    lz4
deps =
    pytest
    mock
    pytest-cov
setenv =
    PYTHONPATH=.
commands = pytest {posargs:tests} --cov barman --cov-report xml:coverage-reports/coverage.xml --cov-report term

[gh-actions]
python =
  3.12: py312
  3.13: py313
  3.14: py314

[testenv:docs]
deps = sphinx
       sphinx-github-style
       sphinxcontrib-apidoc
       pydata-sphinx-theme
       myst_parser
setenv =
    PYTHONPATH=.
passenv = SPHINX_BUILD_DATE
commands = make -C docs {posargs:html man}
allowlist_externals =
    make

[testenv:docs-clean]
deps = sphinx
setenv =
    PYTHONPATH=.
commands = make -C docs clean
allowlist_externals =
    make
