[tox]
envlist = py312, flake8

[testenv]
# extras = all installs barman with every optional dependency
extras = all
deps =
    pytest
    mock
commands = pytest {posargs:tests}
passenv = USER

[testenv:flake8]
commands = flake8 {posargs}
deps = -r tests/requirements_flake8.txt

[flake8]
select = E,F,W,C
ignore = E203, E501, W503
max-line-length = 88
copyright-check = True
copyright-regexp = © Copyright %(author)s (\d{4}-)2025
copyright-author = EnterpriseDB UK Limited
exclude = venv,.tox,build

[testenv:black]
deps = black
commands = black .

[testenv:coverage]
extras = all
deps =
    pytest
    mock
    pytest-cov
setenv =
    PYTHONPATH=.
commands = pytest {posargs:tests} --cov barman --cov-report xml:coverage-reports/coverage.xml --cov-report term

[gh-actions]
python =
  3.12: py312
  3.13: py313
  3.14: py314

[testenv:docs]
deps = sphinx
       sphinx-github-style
       sphinxcontrib-apidoc
       pydata-sphinx-theme
       myst_parser
setenv =
    PYTHONPATH=.
passenv = SPHINX_BUILD_DATE
commands = make -C docs {posargs:html man}
allowlist_externals =
    make

[testenv:docs-clean]
deps = sphinx
setenv =
    PYTHONPATH=.
commands = make -C docs clean
allowlist_externals =
    make
