# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DiagnoseOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _global=None, servers=None):  # noqa: E501
        """DiagnoseOutput - a model defined in OpenAPI

        :param _global: The _global of this DiagnoseOutput.  # noqa: E501
        :type _global: str
        :param servers: The servers of this DiagnoseOutput.  # noqa: E501
        :type servers: str
        """
        self.openapi_types = {
            '_global': str,
            'servers': str
        }

        self.attribute_map = {
            '_global': 'global',
            'servers': 'servers'
        }

        self.__global = _global
        self._servers = servers

    @classmethod
    def from_dict(cls, dikt) -> 'DiagnoseOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagnoseOutput of this DiagnoseOutput.  # noqa: E501
        :rtype: DiagnoseOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _global(self):
        """Gets the _global of this DiagnoseOutput.


        :return: The _global of this DiagnoseOutput.
        :rtype: str
        """
        return self.__global

    @_global.setter
    def _global(self, _global):
        """Sets the _global of this DiagnoseOutput.


        :param _global: The _global of this DiagnoseOutput.
        :type _global: str
        """
        if _global is None:
            raise ValueError("Invalid value for `_global`, must not be `None`")  # noqa: E501

        self.__global = _global

    @property
    def servers(self):
        """Gets the servers of this DiagnoseOutput.


        :return: The servers of this DiagnoseOutput.
        :rtype: str
        """
        return self._servers

    @servers.setter
    def servers(self, servers):
        """Sets the servers of this DiagnoseOutput.


        :param servers: The servers of this DiagnoseOutput.
        :type servers: str
        """
        if servers is None:
            raise ValueError("Invalid value for `servers`, must not be `None`")  # noqa: E501

        self._servers = servers
