---
name: Black

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: "Black"
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository
        uses: actions/checkout@v2
      - name: Step 2 - Apply Black
        uses: psf/black@stable
        with:
          options: ""
      - name: Step 3 - Check if changes
        id: git-status
        shell: bash
        run: |
          if [[ -n $(git status --porcelain) ]]
          then
            echo "::set-output name=status::true"
          fi
      - name: Step 4 - Commit changes
        if: contains(steps.git-status.outputs.status, 'true')
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: "black: reformat source code"
          push: true
