###
##  Foundation-security BlackDuck workflow 
#
name: Foundation-Security/Black Duck Scan

on:
  push:
    tags:        
      - '**'
  workflow_dispatch:

jobs:
  Blackduck-Scan:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source repository
      id: checkout-source
      uses: actions/checkout@v3

    - name: Checkout foundation repository
      id: checkout-foundation
      uses: actions/checkout@v3
      with:
          repository: EnterpriseDB/foundation-packaging
          ref: main
          path: foundation
          token: ${{secrets.GH_SLONIK}}

    - name: Set defaults
      id: set-default
      shell: bash
      run: |
        echo "foundation_scanning_blackduck_java-distribution=adopt" >> $GITHUB_ENV;
        echo "foundation_scanning_blackduck_java-version=11" >> $GITHUB_ENV;
        echo "foundation_scanning_blackduck_detect-version=8.2.0" >> $GITHUB_ENV;
        echo "foundation_scanning_blackduck_scan-mode=INTELLIGENT" >> $GITHUB_ENV;

    - name: Get foundation config
      id: get-foundation-config
      uses: ./foundation/actions/get/foundation-config
      continue-on-error: true     
        
    - name: Set up JDK
      id: setup-jdk
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.foundation_scanning_blackduck_java-distribution }}
        java-version: ${{ env.foundation_scanning_blackduck_java-version }}
       
    - name: Run Synopsys Detect
      id: run-synopsys-detect
      uses: synopsys-sig/detect-action@v0.3.3
      env:
        DETECT.PROJECT.VERSION.NAME: ${{ github.ref_type }}/${{ github.ref_name }}
        DETECT.PROJECT.NAME: ${{ github.event.repository.name }}
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        blackduck-url: ${{ secrets.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        detect-version: ${{ env.foundation_scanning_blackduck_detect-version }}
        scan-mode: ${{ env.foundation_scanning_blackduck_scan-mode }}
